name: Justin Baird
favicon: null
layout_spectrum: 0.5
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Justin Baird
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040521'
    - '#2945cc'
    - '#c10f59'
    - '#72bcf9'
    - '#c071c3'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.4667025
purpose: []
